# Generated by Django 5.1.4 on 2025-01-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsmodel',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
