# Generated by Django 5.1.4 on 2025-01-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
