"""0002-Columna de imagen_url

Revision ID: bf41ff4a3202
Revises: e23fc51971e2
Create Date: 2024-12-14 20:29:27.055376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf41ff4a3202'
down_revision = 'e23fc51971e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peliculas', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
